# Generated by Django 3.0.5 on 2020-04-08 17:50

import RiskmapApp.models
import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='nombres')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='apellidos')),
                ('rut', models.IntegerField(help_text='Sin dígito verificador', unique=True, validators=[django.core.validators.MinValueValidator(500000), django.core.validators.MaxValueValidator(100000000)], verbose_name='rut')),
                ('rut_dv', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('K', 'K')], default='0', help_text='Seleccione una opción', max_length=1, validators=[RiskmapApp.models.validate_rut_dv], verbose_name='digito verificador')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('birthday', models.DateField(blank=True, help_text='Quien autoriza la inscripción de este usuario', null=True, verbose_name='fecha de nacimiento')),
                ('end_period', models.DateTimeField(default=datetime.datetime(2020, 10, 1, 2, 59, 59, tzinfo=utc), help_text='Momento en que la cuenta expira (mínimo 15 minutos)', verbose_name='expiración')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True, help_text='Desactive para forzar expiración del usuario', verbose_name='Usuario Activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Es administrador')),
                ('supervisor', models.CharField(blank=True, help_text='En la unidad', max_length=30, verbose_name='supervisor')),
                ('authorization', models.CharField(blank=True, help_text='Quien autoriza la inscripción de este usuario (vacío si es el mismo supervisor)', max_length=50, verbose_name='autoriza')),
                ('position', models.CharField(blank=True, help_text='En la unidad', max_length=50, verbose_name='cargo')),
                ('department', models.CharField(blank=True, help_text='Unidad en la cual trabaja', max_length=50, verbose_name='unidad')),
                ('groups', models.ManyToManyField(blank=True, related_name='groups', to='auth.Group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
